namespace Ray1Map.Jade {
	public enum TEXT_Language : int {
		Français = 0,
        English = 1,
        Dansk = 2,
        Nederlands = 3,
        Suomi = 4,
        Deutsch = 5,
        Italiano = 6,
        Español = 7,
        Portuguese = 8,
        Svenska = 9,
        Polski = 10,
        Unknown11 = 11,
        Japanese = 12,
        Chinese = 13,
        Albanian = 14,
        Arabic = 15,
        Bulgarian = 16,
        Byelorussian = 17,
        Greek = 18,
        Korean = 19,
        Norsk = 20,
        Romanian = 21,
        Serbian = 22,
        Slovak = 23,
        Slovenian = 24,
        Turkish = 25,
        Czech = 26,
        Hungarian = 27,
        Taiwanese = 28,
        Unknown29 = 29,
        Unknown30 = 30,
    }
}
