namespace R1Engine
{
    // Event types have to be ushorts right now even though this is a byte
    public enum GBA_R3_ActorID : ushort
    {
        Rayman = 0,
        RaymanBody = 1,
        Platform_Bouncy = 7,
        Platform_Moving_Vertical = 8,
        Switch = 10,
        LockedDoor = 11,
        Lum = 12,
        Cage = 13,
        LevelCurtain = 14,
        Keg = 18,
        SphereBase = 20,
        Sphere = 21,
        Pirate_Green = 23,
        Pirate_Blue = 24,
        Pirate_Red = 25,
        HelicopterBomb = 26,
        ZombieChicken = 27,
        LevelExit_Back = 30,
        Caterpillar = 35,
        Butterfly = 37,
        Boss_Jano = 39,
        Spider = 41,
        Ring = 47,
        Effect_49 = 49,
        Breakable_Ground = 50,
        Plum = 54,
        DarkLum = 57,
        SpikyBall_Hovering = 60,
        Murfy = 64,
        Effect_67 = 67,
        Shell_Walking = 76,
        Ly = 78,
        Breakable_Wall = 81,
        Boss_Machine = 84,
        Shell_Flying = 88,
        MovingSkull = 89,
        SpikyBall_Swinging = 91,
        MurfyStone = 92,
        Boss_Grolgoth = 93,
        Teensies = 95,
        LevelExit_Next = 101,
        Rayman_WorldMap = 103,
    }
}