using Cysharp.Threading.Tasks;
using R1Engine.Jade;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;

namespace R1Engine
{
    public class Jade_MyWordCoach_Wii_Manager : Jade_Montreal_BaseManager {

		// Game actions
		public override GameAction[] GetGameActions(GameSettings settings) {
			return base.GetGameActions(settings).Concat(new GameAction[]
			{
				new GameAction("Export textures (unbinarized)", false, true, (input, output) => ExportTexturesUnbinarized(settings, output)),
			}).ToArray();
		}

		// Levels
		public override LevelInfo[] LevelInfos => new LevelInfo[] {
			new LevelInfo(0x3500235C, "ROOT/Bin", "Alastair_Perso_Lighting_wow_ff05235c.bin", worldName: "WOW", mapName: "Alastair_Perso_Lighting", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x35002492, "ROOT/Bin", "AlastairScene_wow_ff052492.bin", worldName: "WOW", mapName: "AlastairScene", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x05003D8B, "ROOT/Bin", "AllAlastairStuff_wol_ff053d8b.bin", worldName: "WOL", mapName: "AllAlastairStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x05003D8F, "ROOT/Bin", "AllAlastairStuff_wol_ff053d8f.bin", worldName: "WOL", mapName: "AllAlastairStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x0900296D, "ROOT/Bin", "AllAlastairStuff_wol_ff09296d.bin", worldName: "WOL", mapName: "AllAlastairStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x35003D75, "ROOT/Bin", "AllAlastairStuff_wow_ff053d75.bin", worldName: "WOW", mapName: "AllAlastairStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x35003D90, "ROOT/Bin", "AllAlastairStuff_wow_ff053d90.bin", worldName: "WOW", mapName: "AllAlastairStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002956, "ROOT/Bin", "AllAlastairStuff_wow_ff092956.bin", worldName: "WOW", mapName: "AllAlastairStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x05003D8C, "ROOT/Bin", "AllLuciusStuff_wol_ff053d8c.bin", worldName: "WOL", mapName: "AllLuciusStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x05003D97, "ROOT/Bin", "AllLuciusStuff_wol_ff053d97.bin", worldName: "WOL", mapName: "AllLuciusStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x0900296E, "ROOT/Bin", "AllLuciusStuff_wol_ff09296e.bin", worldName: "WOL", mapName: "AllLuciusStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x35003D7C, "ROOT/Bin", "AllLuciusStuff_wow_ff053d7c.bin", worldName: "WOW", mapName: "AllLuciusStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x35003D98, "ROOT/Bin", "AllLuciusStuff_wow_ff053d98.bin", worldName: "WOW", mapName: "AllLuciusStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900295D, "ROOT/Bin", "AllLuciusStuff_wow_ff09295d.bin", worldName: "WOW", mapName: "AllLuciusStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x05003D8D, "ROOT/Bin", "AllPennyStuff_wol_ff053d8d.bin", worldName: "WOL", mapName: "AllPennyStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x05003D9F, "ROOT/Bin", "AllPennyStuff_wol_ff053d9f.bin", worldName: "WOL", mapName: "AllPennyStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x0900296F, "ROOT/Bin", "AllPennyStuff_wol_ff09296f.bin", worldName: "WOL", mapName: "AllPennyStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x35003D83, "ROOT/Bin", "AllPennyStuff_wow_ff053d83.bin", worldName: "WOW", mapName: "AllPennyStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x35003DA0, "ROOT/Bin", "AllPennyStuff_wow_ff053da0.bin", worldName: "WOW", mapName: "AllPennyStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002964, "ROOT/Bin", "AllPennyStuff_wow_ff092964.bin", worldName: "WOW", mapName: "AllPennyStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x05003D8E, "ROOT/Bin", "AllVeronicaStuff_wol_ff053d8e.bin", worldName: "WOL", mapName: "AllVeronicaStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x05003DA7, "ROOT/Bin", "AllVeronicaStuff_wol_ff053da7.bin", worldName: "WOL", mapName: "AllVeronicaStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x09002970, "ROOT/Bin", "AllVeronicaStuff_wol_ff092970.bin", worldName: "WOL", mapName: "AllVeronicaStuff", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x35003D8A, "ROOT/Bin", "AllVeronicaStuff_wow_ff053d8a.bin", worldName: "WOW", mapName: "AllVeronicaStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x35003DA8, "ROOT/Bin", "AllVeronicaStuff_wow_ff053da8.bin", worldName: "WOW", mapName: "AllVeronicaStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900296B, "ROOT/Bin", "AllVeronicaStuff_wow_ff09296b.bin", worldName: "WOW", mapName: "AllVeronicaStuff", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002137, "ROOT/Bin", "AnimsAlastair0_wow_ff092137.bin", worldName: "WOW", mapName: "AnimsAlastair0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021DA, "ROOT/Bin", "AnimsAlastair0_wow_ff0921da.bin", worldName: "WOW", mapName: "AnimsAlastair0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002988, "ROOT/Bin", "AnimsAlastair0_wow_ff092988.bin", worldName: "WOW", mapName: "AnimsAlastair0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002141, "ROOT/Bin", "AnimsAlastair1_wow_ff092141.bin", worldName: "WOW", mapName: "AnimsAlastair1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021E1, "ROOT/Bin", "AnimsAlastair1_wow_ff0921e1.bin", worldName: "WOW", mapName: "AnimsAlastair1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390028EC, "ROOT/Bin", "AnimsAlastair1_wow_ff0928ec.bin", worldName: "WOW", mapName: "AnimsAlastair1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900214B, "ROOT/Bin", "AnimsAlastair2_wow_ff09214b.bin", worldName: "WOW", mapName: "AnimsAlastair2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021E8, "ROOT/Bin", "AnimsAlastair2_wow_ff0921e8.bin", worldName: "WOW", mapName: "AnimsAlastair2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390028F3, "ROOT/Bin", "AnimsAlastair2_wow_ff0928f3.bin", worldName: "WOW", mapName: "AnimsAlastair2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002155, "ROOT/Bin", "AnimsAlastair3_wow_ff092155.bin", worldName: "WOW", mapName: "AnimsAlastair3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021EF, "ROOT/Bin", "AnimsAlastair3_wow_ff0921ef.bin", worldName: "WOW", mapName: "AnimsAlastair3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390028FB, "ROOT/Bin", "AnimsAlastair3_wow_ff0928fb.bin", worldName: "WOW", mapName: "AnimsAlastair3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900215F, "ROOT/Bin", "AnimsLucius0_wow_ff09215f.bin", worldName: "WOW", mapName: "AnimsLucius0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021F6, "ROOT/Bin", "AnimsLucius0_wow_ff0921f6.bin", worldName: "WOW", mapName: "AnimsLucius0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002902, "ROOT/Bin", "AnimsLucius0_wow_ff092902.bin", worldName: "WOW", mapName: "AnimsLucius0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002169, "ROOT/Bin", "AnimsLucius1_wow_ff092169.bin", worldName: "WOW", mapName: "AnimsLucius1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021FD, "ROOT/Bin", "AnimsLucius1_wow_ff0921fd.bin", worldName: "WOW", mapName: "AnimsLucius1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002909, "ROOT/Bin", "AnimsLucius1_wow_ff092909.bin", worldName: "WOW", mapName: "AnimsLucius1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002173, "ROOT/Bin", "AnimsLucius2_wow_ff092173.bin", worldName: "WOW", mapName: "AnimsLucius2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002204, "ROOT/Bin", "AnimsLucius2_wow_ff092204.bin", worldName: "WOW", mapName: "AnimsLucius2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002910, "ROOT/Bin", "AnimsLucius2_wow_ff092910.bin", worldName: "WOW", mapName: "AnimsLucius2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900217D, "ROOT/Bin", "AnimsLucius3_wow_ff09217d.bin", worldName: "WOW", mapName: "AnimsLucius3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900220B, "ROOT/Bin", "AnimsLucius3_wow_ff09220b.bin", worldName: "WOW", mapName: "AnimsLucius3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002917, "ROOT/Bin", "AnimsLucius3_wow_ff092917.bin", worldName: "WOW", mapName: "AnimsLucius3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002187, "ROOT/Bin", "AnimsPenny0_wow_ff092187.bin", worldName: "WOW", mapName: "AnimsPenny0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002212, "ROOT/Bin", "AnimsPenny0_wow_ff092212.bin", worldName: "WOW", mapName: "AnimsPenny0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900291E, "ROOT/Bin", "AnimsPenny0_wow_ff09291e.bin", worldName: "WOW", mapName: "AnimsPenny0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002191, "ROOT/Bin", "AnimsPenny1_wow_ff092191.bin", worldName: "WOW", mapName: "AnimsPenny1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002219, "ROOT/Bin", "AnimsPenny1_wow_ff092219.bin", worldName: "WOW", mapName: "AnimsPenny1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002925, "ROOT/Bin", "AnimsPenny1_wow_ff092925.bin", worldName: "WOW", mapName: "AnimsPenny1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900219B, "ROOT/Bin", "AnimsPenny2_wow_ff09219b.bin", worldName: "WOW", mapName: "AnimsPenny2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002220, "ROOT/Bin", "AnimsPenny2_wow_ff092220.bin", worldName: "WOW", mapName: "AnimsPenny2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900292C, "ROOT/Bin", "AnimsPenny2_wow_ff09292c.bin", worldName: "WOW", mapName: "AnimsPenny2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021A5, "ROOT/Bin", "AnimsPenny3_wow_ff0921a5.bin", worldName: "WOW", mapName: "AnimsPenny3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002227, "ROOT/Bin", "AnimsPenny3_wow_ff092227.bin", worldName: "WOW", mapName: "AnimsPenny3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002933, "ROOT/Bin", "AnimsPenny3_wow_ff092933.bin", worldName: "WOW", mapName: "AnimsPenny3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021AF, "ROOT/Bin", "AnimsVeronica0_wow_ff0921af.bin", worldName: "WOW", mapName: "AnimsVeronica0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900222E, "ROOT/Bin", "AnimsVeronica0_wow_ff09222e.bin", worldName: "WOW", mapName: "AnimsVeronica0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900293A, "ROOT/Bin", "AnimsVeronica0_wow_ff09293a.bin", worldName: "WOW", mapName: "AnimsVeronica0", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021B9, "ROOT/Bin", "AnimsVeronica1_wow_ff0921b9.bin", worldName: "WOW", mapName: "AnimsVeronica1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002235, "ROOT/Bin", "AnimsVeronica1_wow_ff092235.bin", worldName: "WOW", mapName: "AnimsVeronica1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002941, "ROOT/Bin", "AnimsVeronica1_wow_ff092941.bin", worldName: "WOW", mapName: "AnimsVeronica1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021C3, "ROOT/Bin", "AnimsVeronica2_wow_ff0921c3.bin", worldName: "WOW", mapName: "AnimsVeronica2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900223C, "ROOT/Bin", "AnimsVeronica2_wow_ff09223c.bin", worldName: "WOW", mapName: "AnimsVeronica2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002948, "ROOT/Bin", "AnimsVeronica2_wow_ff092948.bin", worldName: "WOW", mapName: "AnimsVeronica2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x390021CD, "ROOT/Bin", "AnimsVeronica3_wow_ff0921cd.bin", worldName: "WOW", mapName: "AnimsVeronica3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x39002243, "ROOT/Bin", "AnimsVeronica3_wow_ff092243.bin", worldName: "WOW", mapName: "AnimsVeronica3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3900294F, "ROOT/Bin", "AnimsVeronica3_wow_ff09294f.bin", worldName: "WOW", mapName: "AnimsVeronica3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x54000160, "ROOT/Bin", "BackLight_wow_ff040160.bin", worldName: "WOW", mapName: "BackLight", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x66038E8A, "ROOT/Bin", "Base_wow_ff068e8a.bin", worldName: "WOW", mapName: "Base", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x030002C2, "ROOT/Bin", "Competition_VS_wol_ff0302c2.bin", worldName: "WOL", mapName: "Competition_VS", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x230002C1, "ROOT/Bin", "Competition_VS_wow_ff0302c1.bin", worldName: "WOW", mapName: "Competition_VS", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x03000209, "ROOT/Bin", "Competition_wol_ff030209.bin", worldName: "WOL", mapName: "Competition", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x23000208, "ROOT/Bin", "Competition_wow_ff030208.bin", worldName: "WOW", mapName: "Competition", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x2F0001C7, "ROOT/Bin", "Dictionary_Manager_wow_ff0f01c7.bin", worldName: "WOW", mapName: "Dictionary_Manager", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x32042406, "ROOT/Bin", "GameConfig_SplitDecision_wow_ff022406.bin", worldName: "WOW", mapName: "GameConfig_SplitDecision", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x2E029FE9, "ROOT/Bin", "GameConfig_WordTris_wow_ff0e9fe9.bin", worldName: "WOW", mapName: "GameConfig_WordTris", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x09006AD5, "ROOT/Bin", "GameInterface_Manager_wow_ff096ad5.bin", worldName: "WOW", mapName: "GameInterface_Manager", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x66038E5E, "ROOT/Bin", "Global_wow_ff068e5e.bin", worldName: "WOW", mapName: "Global", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009CD9, "ROOT/Bin", "Gym_MissingLetter_wol_ff0e9cd9.bin", worldName: "WOL", mapName: "Gym_MissingLetter", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029CD8, "ROOT/Bin", "Gym_MissingLetter_wow_ff0e9cd8.bin", worldName: "WOW", mapName: "Gym_MissingLetter", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x07000085, "ROOT/Bin", "Gym_MissingLetters_VS_wol_ff070085.bin", worldName: "WOL", mapName: "Gym_MissingLetters_VS", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x27000084, "ROOT/Bin", "Gym_MissingLetters_VS_wow_ff070084.bin", worldName: "WOW", mapName: "Gym_MissingLetters_VS", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0700012F, "ROOT/Bin", "Gym_PastaLetters_VS_wol_ff07012f.bin", worldName: "WOL", mapName: "Gym_PastaLetters_VS", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2700012E, "ROOT/Bin", "Gym_PastaLetters_VS_wow_ff07012e.bin", worldName: "WOW", mapName: "Gym_PastaLetters_VS", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x07000033, "ROOT/Bin", "Gym_PastaLetters_wol_ff070033.bin", worldName: "WOL", mapName: "Gym_PastaLetters", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x27000032, "ROOT/Bin", "Gym_PastaLetters_wow_ff070032.bin", worldName: "WOW", mapName: "Gym_PastaLetters", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x02001FA5, "ROOT/Bin", "Gym_SplitDecision_wol_ff021fa5.bin", worldName: "WOL", mapName: "Gym_SplitDecision", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x32041FA4, "ROOT/Bin", "Gym_SplitDecision_wow_ff021fa4.bin", worldName: "WOW", mapName: "Gym_SplitDecision", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009D78, "ROOT/Bin", "Gym_WordTris_VS_wol_ff0e9d78.bin", worldName: "WOL", mapName: "Gym_WordTris_VS", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029D77, "ROOT/Bin", "Gym_WordTris_VS_wow_ff0e9d77.bin", worldName: "WOW", mapName: "Gym_WordTris_VS", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009D54, "ROOT/Bin", "Gym_WordTris_wol_ff0e9d54.bin", worldName: "WOL", mapName: "Gym_WordTris", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029D53, "ROOT/Bin", "Gym_WordTris_wow_ff0e9d53.bin", worldName: "WOW", mapName: "Gym_WordTris", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0F000153, "ROOT/Bin", "InGameMenus_wol_ff0f0153.bin", worldName: "WOL", mapName: "InGameMenus", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2F000152, "ROOT/Bin", "InGameMenus_wow_ff0f0152.bin", worldName: "WOW", mapName: "InGameMenus", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x4F00076F, "ROOT/Bin", "Input_Manager_wow_ff0f076f.bin", worldName: "WOW", mapName: "Input_Manager", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x2F0003FB, "ROOT/Bin", "Legend_Manager_wow_ff0f03fb.bin", worldName: "WOW", mapName: "Legend_Manager", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x35002363, "ROOT/Bin", "Lucius_Perso_Lighting_wow_ff052363.bin", worldName: "WOW", mapName: "Lucius_Perso_Lighting", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x35002499, "ROOT/Bin", "LuciusScene_wow_ff052499.bin", worldName: "WOW", mapName: "LuciusScene", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009DCC, "ROOT/Bin", "MissingLetter_L1_wol_ff0e9dcc.bin", worldName: "WOL", mapName: "MissingLetter_L1", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029DBD, "ROOT/Bin", "MissingLetter_L1_wow_ff0e9dbd.bin", worldName: "WOW", mapName: "MissingLetter_L1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009DCE, "ROOT/Bin", "MissingLetter_L2_wol_ff0e9dce.bin", worldName: "WOL", mapName: "MissingLetter_L2", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029DC4, "ROOT/Bin", "MissingLetter_L2_wow_ff0e9dc4.bin", worldName: "WOW", mapName: "MissingLetter_L2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009DCD, "ROOT/Bin", "MissingLetter_L3_wol_ff0e9dcd.bin", worldName: "WOL", mapName: "MissingLetter_L3", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029DCB, "ROOT/Bin", "MissingLetter_L3_wow_ff0e9dcb.bin", worldName: "WOW", mapName: "MissingLetter_L3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E00, "ROOT/Bin", "MissingLetters_VS_L1_wol_ff0e9e00.bin", worldName: "WOL", mapName: "MissingLetters_VS_L1", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029DEA, "ROOT/Bin", "MissingLetters_VS_L1_wow_ff0e9dea.bin", worldName: "WOW", mapName: "MissingLetters_VS_L1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E01, "ROOT/Bin", "MissingLetters_VS_L2_wol_ff0e9e01.bin", worldName: "WOL", mapName: "MissingLetters_VS_L2", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029DF1, "ROOT/Bin", "MissingLetters_VS_L2_wow_ff0e9df1.bin", worldName: "WOW", mapName: "MissingLetters_VS_L2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E02, "ROOT/Bin", "MissingLetters_VS_L3_wol_ff0e9e02.bin", worldName: "WOL", mapName: "MissingLetters_VS_L3", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029DFF, "ROOT/Bin", "MissingLetters_VS_L3_wow_ff0e9dff.bin", worldName: "WOW", mapName: "MissingLetters_VS_L3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009F51, "ROOT/Bin", "MyDefinition_L1_wol_ff0e9f51.bin", worldName: "WOL", mapName: "MyDefinition_L1", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029F42, "ROOT/Bin", "MyDefinition_L1_wow_ff0e9f42.bin", worldName: "WOW", mapName: "MyDefinition_L1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009F52, "ROOT/Bin", "MyDefinition_L2_wol_ff0e9f52.bin", worldName: "WOL", mapName: "MyDefinition_L2", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029F49, "ROOT/Bin", "MyDefinition_L2_wow_ff0e9f49.bin", worldName: "WOW", mapName: "MyDefinition_L2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009F53, "ROOT/Bin", "MyDefinition_L3_wol_ff0e9f53.bin", worldName: "WOL", mapName: "MyDefinition_L3", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029F50, "ROOT/Bin", "MyDefinition_L3_wow_ff0e9f50.bin", worldName: "WOW", mapName: "MyDefinition_L3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x070001C3, "ROOT/Bin", "MyDefinition_VS_wol_ff0701c3.bin", worldName: "WOL", mapName: "MyDefinition_VS", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x270001C2, "ROOT/Bin", "MyDefinition_VS_wow_ff0701c2.bin", worldName: "WOW", mapName: "MyDefinition_VS", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x27000FF5, "ROOT/Bin", "Nitro_Manager_wow_ff070ff5.bin", worldName: "WOW", mapName: "Nitro_Manager", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E87, "ROOT/Bin", "PastaLetters_L1_wol_ff0e9e87.bin", worldName: "WOL", mapName: "PastaLetters_L1", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029E78, "ROOT/Bin", "PastaLetters_L1_wow_ff0e9e78.bin", worldName: "WOW", mapName: "PastaLetters_L1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E88, "ROOT/Bin", "PastaLetters_L2_wol_ff0e9e88.bin", worldName: "WOL", mapName: "PastaLetters_L2", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029E7F, "ROOT/Bin", "PastaLetters_L2_wow_ff0e9e7f.bin", worldName: "WOW", mapName: "PastaLetters_L2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E89, "ROOT/Bin", "PastaLetters_L3_wol_ff0e9e89.bin", worldName: "WOL", mapName: "PastaLetters_L3", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029E86, "ROOT/Bin", "PastaLetters_L3_wow_ff0e9e86.bin", worldName: "WOW", mapName: "PastaLetters_L3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x3500236A, "ROOT/Bin", "Penny_Perso_Lighting_wow_ff05236a.bin", worldName: "WOW", mapName: "Penny_Perso_Lighting", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x350024A0, "ROOT/Bin", "PennyScene_wow_ff0524a0.bin", worldName: "WOW", mapName: "PennyScene", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0F0002C4, "ROOT/Bin", "PreGameMenus_wol_ff0f02c4.bin", worldName: "WOL", mapName: "PreGameMenus", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2F0002C3, "ROOT/Bin", "PreGameMenus_wow_ff0f02c3.bin", worldName: "WOW", mapName: "PreGameMenus", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009ECA, "ROOT/Bin", "SafeCracker_L1_wol_ff0e9eca.bin", worldName: "WOL", mapName: "SafeCracker_L1", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029EBB, "ROOT/Bin", "SafeCracker_L1_wow_ff0e9ebb.bin", worldName: "WOW", mapName: "SafeCracker_L1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009ECB, "ROOT/Bin", "SafeCracker_L2_wol_ff0e9ecb.bin", worldName: "WOL", mapName: "SafeCracker_L2", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029EC2, "ROOT/Bin", "SafeCracker_L2_wow_ff0e9ec2.bin", worldName: "WOW", mapName: "SafeCracker_L2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009ECC, "ROOT/Bin", "SafeCracker_L3_wol_ff0e9ecc.bin", worldName: "WOL", mapName: "SafeCracker_L3", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029EC9, "ROOT/Bin", "SafeCracker_L3_wow_ff0e9ec9.bin", worldName: "WOW", mapName: "SafeCracker_L3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009ECD, "ROOT/Bin", "SafeCracker_VS_L1_wol_ff0e9ecd.bin", worldName: "WOL", mapName: "SafeCracker_VS_L1", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029EA6, "ROOT/Bin", "SafeCracker_VS_L1_wow_ff0e9ea6.bin", worldName: "WOW", mapName: "SafeCracker_VS_L1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x35001FFA, "ROOT/Bin", "ScriptedEventsBase_wow_ff051ffa.bin", worldName: "WOW", mapName: "ScriptedEventsBase", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x2F001F69, "ROOT/Bin", "SE_Manager_wow_ff0f1f69.bin", worldName: "WOW", mapName: "SE_Manager", type: LevelInfo.FileType.WOW),
			new LevelInfo(0xA200046E, "ROOT/Bin", "Sound_Manager_wow_ff02046e.bin", worldName: "WOW", mapName: "Sound_Manager", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x32042AAD, "ROOT/Bin", "SoundConfig_MissingLetters_VS_wow_ff022aad.bin", worldName: "WOW", mapName: "SoundConfig_MissingLetters_VS", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x2700024F, "ROOT/Bin", "SoundConfig_MissingLetters_wow_ff07024f.bin", worldName: "WOW", mapName: "SoundConfig_MissingLetters", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x230002D8, "ROOT/Bin", "SoundConfig_MyDefinition_wow_ff0302d8.bin", worldName: "WOW", mapName: "SoundConfig_MyDefinition", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x27000242, "ROOT/Bin", "SoundConfig_PastaLetters_wow_ff070242.bin", worldName: "WOW", mapName: "SoundConfig_PastaLetters", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x230002FE, "ROOT/Bin", "SoundConfig_SafeCracker_wow_ff0302fe.bin", worldName: "WOW", mapName: "SoundConfig_SafeCracker", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x320423C6, "ROOT/Bin", "SoundConfig_SplitDecision_wow_ff0223c6.bin", worldName: "WOW", mapName: "SoundConfig_SplitDecision", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x2E029F24, "ROOT/Bin", "SoundConfig_WordTris_wow_ff0e9f24.bin", worldName: "WOW", mapName: "SoundConfig_WordTris", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E5A, "ROOT/Bin", "SplitDecision_L1_wol_ff0e9e5a.bin", worldName: "WOL", mapName: "SplitDecision_L1", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029E4B, "ROOT/Bin", "SplitDecision_L1_wow_ff0e9e4b.bin", worldName: "WOW", mapName: "SplitDecision_L1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E5B, "ROOT/Bin", "SplitDecision_L2_wol_ff0e9e5b.bin", worldName: "WOL", mapName: "SplitDecision_L2", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029E52, "ROOT/Bin", "SplitDecision_L2_wow_ff0e9e52.bin", worldName: "WOW", mapName: "SplitDecision_L2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E5C, "ROOT/Bin", "SplitDecision_L3_wol_ff0e9e5c.bin", worldName: "WOL", mapName: "SplitDecision_L3", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029E59, "ROOT/Bin", "SplitDecision_L3_wow_ff0e9e59.bin", worldName: "WOW", mapName: "SplitDecision_L3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x2E02A035, "ROOT/Bin", "Transition_Manager_wow_ff0ea035.bin", worldName: "WOW", mapName: "Transition_Manager", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0500247F, "ROOT/Bin", "UnloadDummy_wol_ff05247f.bin", worldName: "WOL", mapName: "UnloadDummy", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x3500247E, "ROOT/Bin", "UnloadDummy_wow_ff05247e.bin", worldName: "WOW", mapName: "UnloadDummy", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x35002371, "ROOT/Bin", "Veronica_Perso_Lighting_wow_ff052371.bin", worldName: "WOW", mapName: "Veronica_Perso_Lighting", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x350024A7, "ROOT/Bin", "VeronicaScene_wow_ff0524a7.bin", worldName: "WOW", mapName: "VeronicaScene", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E2D, "ROOT/Bin", "WordTris_L1_wol_ff0e9e2d.bin", worldName: "WOL", mapName: "WordTris_L1", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029E1E, "ROOT/Bin", "WordTris_L1_wow_ff0e9e1e.bin", worldName: "WOW", mapName: "WordTris_L1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E2E, "ROOT/Bin", "WordTris_L2_wol_ff0e9e2e.bin", worldName: "WOL", mapName: "WordTris_L2", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029E25, "ROOT/Bin", "WordTris_L2_wow_ff0e9e25.bin", worldName: "WOW", mapName: "WordTris_L2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009E2F, "ROOT/Bin", "WordTris_L3_wol_ff0e9e2f.bin", worldName: "WOL", mapName: "WordTris_L3", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029E2C, "ROOT/Bin", "WordTris_L3_wow_ff0e9e2c.bin", worldName: "WOW", mapName: "WordTris_L3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009FB9, "ROOT/Bin", "WordTris_Panic_L1_wol_ff0e9fb9.bin", worldName: "WOL", mapName: "WordTris_Panic_L1", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029FAA, "ROOT/Bin", "WordTris_Panic_L1_wow_ff0e9faa.bin", worldName: "WOW", mapName: "WordTris_Panic_L1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009FBA, "ROOT/Bin", "WordTris_Panic_L2_wol_ff0e9fba.bin", worldName: "WOL", mapName: "WordTris_Panic_L2", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029FB1, "ROOT/Bin", "WordTris_Panic_L2_wow_ff0e9fb1.bin", worldName: "WOW", mapName: "WordTris_Panic_L2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009FBB, "ROOT/Bin", "WordTris_Panic_L3_wol_ff0e9fbb.bin", worldName: "WOL", mapName: "WordTris_Panic_L3", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029FB8, "ROOT/Bin", "WordTris_Panic_L3_wow_ff0e9fb8.bin", worldName: "WOW", mapName: "WordTris_Panic_L3", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009F83, "ROOT/Bin", "WordTris_VS_L1_wol_ff0e9f83.bin", worldName: "WOL", mapName: "WordTris_VS_L1", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029F74, "ROOT/Bin", "WordTris_VS_L1_wow_ff0e9f74.bin", worldName: "WOW", mapName: "WordTris_VS_L1", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009F84, "ROOT/Bin", "WordTris_VS_L2_wol_ff0e9f84.bin", worldName: "WOL", mapName: "WordTris_VS_L2", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029F7B, "ROOT/Bin", "WordTris_VS_L2_wow_ff0e9f7b.bin", worldName: "WOW", mapName: "WordTris_VS_L2", type: LevelInfo.FileType.WOW),
			new LevelInfo(0x0E009F85, "ROOT/Bin", "WordTris_VS_L3_wol_ff0e9f85.bin", worldName: "WOL", mapName: "WordTris_VS_L3", type: LevelInfo.FileType.WOL),
			new LevelInfo(0x2E029F82, "ROOT/Bin", "WordTris_VS_L3_wow_ff0e9f82.bin", worldName: "WOW", mapName: "WordTris_VS_L3", type: LevelInfo.FileType.WOW),
		};

		public override string[] BFFiles => new string[] {
			"DATA/spree.bf"
		};
	}
}
